# Generated by Django 5.0.6 on 2024-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
